name: deploying my portfolio site to my webserver

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    name: deploying on webserver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: "., !.gitignore, !.git, !.github"
          target: ${{ secrets.REMOTE_TARGET }}